
source 'https://github.com/CocoaPods/Specs.git'


target 'monosdktesting_Example' do
    use_frameworks!
    pod_install
  pod 'monosdktesting', :path => '../'

  target 'monosdktesting_Tests' do
    inherit! :search_paths

  end
end
